# This is an example of the most basic config
# that will mimic what PgBouncer does in transaction mode with one server.

[general]

host = "0.0.0.0"
port = 6433
admin_username = "jdoe"
admin_password = "pgcat"
admin_auth_type = "ldap"
admin_auth_ldapurl = "ldap://127.0.0.1:3893"
admin_auth_ldapsuffix  = "@example.com"

[pools.pgml.users.0]
username = "jdoe"
password = "postgres"
auth_type = "ldap"
auth_ldapurl = "ldap://127.0.0.1:3893"
auth_ldapsuffix  = "@example.com"
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"

[pools.pgml.shards.0]
servers = [
  ["127.0.0.1", 28815, "primary"]
]
database = "postgres"
