# This is an example of the most basic config
# that will mimic what PgBouncer does in transaction mode with one server.

[general]

host = "0.0.0.0"
port = 6432
admin_username = "pgcat"
admin_password = "pgcat"
admin_address_whitelist = [
  "0.0.0.0/0"
]

[pools.pgml.users.0]
username = "ip_whitelist"
password = "ip_whitelist"
server_username = "postgres"
address_whitelist = [
  "127.0.0.1",
]
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"

[pools.pgml.users.1]
username = "hostname_whitelist"
password = "hostname_whitelist"
server_username = "postgres"
address_whitelist = [
  "localhost"
]
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"

[pools.pgml.users.2]
username = "private_ip_range_whitelist"
password = "private_ip_range_whitelist"
server_username = "postgres"
address_whitelist = [
  "127.0.0.1/32"
]
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"

[pools.pgml.users.3]
username = "public_ip_range_whitelist"
password = "public_ip_range_whitelist"
server_username = "postgres"
address_whitelist = [
  "0.0.0.0/0"
]
pool_size = 10
min_pool_size = 1
pool_mode = "transaction"

[pools.pgml.shards.0]
servers = [
  ["127.0.0.1", 9876, "primary"]
]
database = "postgres"
